import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "@/styles/globals.css";

const urbanist = Urbanist({
  subsets: ["latin"],
  display: 'swap',
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
